import LegalPage from '../components/LegalPage'
import useMeta from '../hooks/useMeta'
import { SITE_URL, SUPPORT_EMAIL } from '../data/content'

// Template legal text - needs lawyer review before launch.

export default function RiskDisclosure() {
  useMeta({
    title: 'Risk Disclosure - Greenwood Finlore',
    description:
      'Read the Greenwood Finlore Risk Disclosure covering the substantial risks of trading cryptocurrencies, forex and CFDs.',
    keywords: 'Greenwood Finlore risk disclosure, crypto trading risks Australia',
    canonical: `${SITE_URL}risk-disclosure`,
  })

  return (
    <LegalPage title="Risk Disclosure">
      <p>Last updated: September 2026</p>

      <h2>1. Market Volatility</h2>
      <p>
        The prices of cryptocurrencies and other digital assets are highly volatile. Values can
        rise or fall dramatically in very short periods, and movements are often unpredictable.
        You should never trade with funds you cannot afford to lose.
      </p>

      <h2>2. Leverage</h2>
      <p>
        Some instruments offered on the platform may involve leverage. While leverage can magnify
        gains, it also magnifies losses, which can exceed your initial deposit. Ensure you fully
        understand how leverage works before using it.
      </p>

      <h2>3. Loss Of Capital</h2>
      <p>
        Trading involves a real risk of losing part or all of your invested capital. Past
        performance of any asset, strategy or trader is not a reliable indicator of future
        results.
      </p>

      <h2>4. Past Performance</h2>
      <p>
        Historical returns, accuracy figures, growth projections and testimonials shown on this
        website are illustrative marketing material. They do not guarantee future results and
        should not be the basis of an investment decision.
      </p>

      <h2>5. AI Projections</h2>
      <p>
        Signals and projections generated by our AI systems are estimates based on historical
        data and statistical models. They may be wrong, may lag market events and are provided
        for information only. No automated system can guarantee profits.
      </p>

      <h2>6. No Investment Advice</h2>
      <p>
        Greenwood Finlore is not a financial services firm and is not authorised to provide
        financial advice. Nothing on this website constitutes a recommendation to buy, sell or
        hold any asset. Consult an independent licensed advisor before making investment
        decisions.
      </p>

      <h2>7. Jurisdictional Restrictions</h2>
      <p>
        The services described on this website may not be available in all jurisdictions. It is
        your responsibility to confirm that using the platform complies with the laws and
        regulations applicable in your country of residence.
      </p>

      <h2>8. Consult A Professional</h2>
      <p>
        If you are unsure about any aspect of trading or about the suitability of this platform
        for your circumstances, seek advice from an independent financial professional before
        proceeding. Questions can also be sent to {SUPPORT_EMAIL}.
      </p>
    </LegalPage>
  )
}
